# Generated by Django 2.1.2 on 2018-11-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rutEmpresa', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
